server:
  port: 9000

spring:
  application:
    name: app2
  zipkin:
    base-url: http://192.168.37.42:9411
    sender:
      type: kafka
  sleuth:
    sampler:
      percentage: 1.0
  kafka:
    bootstrap-servers: kafka001:9092